services:
  mysql-server:
    container_name: mysql-server
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  react-app:
    container_name: react-app
    image: demo-react:full
    depends_on:
      mysql-server:
        condition: service_healthy
    ports:
      - "8080:80"
volumes:
  mysql-data: {}

# Pour lancer l'ensemble des services => docker compose up
# Pour retirer l'ensemble des services => docker compose down