apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-name" . }}-deployment
  labels:
    {{- include "common-labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "common-labels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "app-name" . }}-pod
      labels:
        {{- include "common-labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "app-name" . }}-container
        image: nginx:{{ .Values.nginxVersion }}
        ports:
          - containerPort: 80