apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo-07-nginx-deployment
spec:
  selector:
    matchLabels:
      app: exo-07-nginx
  template:
    metadata:
      name: exo-07-nginx-pod
      labels:
        app: exo-07-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "country"
                    operator: "In"
                    values: ["france"]
      tolerations:
        - key: "country"
          value: "france"
          operator: "Equal"
      containers:
      - name: exo-07-nginx-container
        image: nginx
        ports:
        - containerPort: 80
