apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 9
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      name: demo-pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: demo-container
        image: nginx:alpine
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
          requests:
            memory: "250Mi"
            cpu: "100m"
        ports:
          - containerPort: 80